fix: improve error message for command installation and check for gum installation

diff --git a/script b/script
--- a/script
+++ b/script
@@ -80,7 +80,7 @@ install_cmd_rootless() {
 		rm -rf $TEMP_DIR/$CMD
 		$CMD > /dev/null 2>&1
 		if [ "$?" = "127" ]; then
-			echo "The '$CMD' command, isnt correctly installed"
+			echo "The '$CMD' command needs libraries"
 			echo "Installing with sudo..."
 			sudo apt-get install -y $CMD > /dev/null &&
 			[ -z "$list" ] && echo "$CMD installed successfully"
@@ -241,29 +241,6 @@ quit() {
 	rmdir $TEMP_DIR
 	exit
 }
-update_gum() {
-	[ ! -f $HOME/.local/bin/gum ] && { sudo apt install --only-upgrade gum; return; }
-	command -v jq &> /dev/null || install_cmd_rootless jq
-	repo=charmbracelet/gum
-	echo "Checking for the latest version of $repo..."
-	current_release=$(gum -v | cut -d ' ' -f 3)
-	request=$(curl -s https://api.github.com/repos/$repo/releases/latest)
-	[ "$(echo -E "$request" | jq -er 'select(has("message")) | .message')" ] && return
-	latest_release=$(echo -E "$request" | jq -r ".tag_name")
-	if [ "$current_release" = "$latest_release" ]; then
-		gum style --bold --foreground $secondary --border-foreground $primary --border double --padding "0 1" --align center "$repo is already on the latest version"
-		return
-	fi
-	echo "Downloading $repo..."
-	gum_latest_release=gum_${latest_release#v}_Linux_x86_64
-	download_url=$(echo -E "$request" | jq -r '.assets[].browser_download_url | select(endswith("Linux_x86_64.tar.gz"))')
-	wget -q --show-progress "$download_url"
-	tar -xzf $gum_latest_release.tar.gz
-	rm $HOME/.local/bin/gum
-	mv $gum_latest_release/gum $HOME/.local/bin
-	rm -rf $gum_latest_release.tar.gz $gum_latest_release
-	echo "$repo successfully updated"
-}
 show_script_code() {
 	curl -s https://raw.githubusercontent.com/andrexandre/script/refs/heads/main/script | gum pager
 }
@@ -375,6 +352,7 @@ download_am() {
 	curl -so $OLDPWD/am https://raw.githubusercontent.com/andrexandre/alias-manager/refs/heads/main/am
 }
 main() {
+	! command -v gum &> /dev/null && echo gum not installed && return
 	gum style --bold --border double --padding "0 1" --align center "Welcome to the Linux setup script!"
 	while true; do
 		REPLY=$(gum choose --header="$user_prompt" install configure system mode options $quit_view_code quit)
@@ -396,7 +374,7 @@ main() {
 				;;
 			options)
 				REPLY=$(gum choose --header="$user_prompt" $start_view_code show_script_code \
-					update_gum about download_am back)
+					about download_am back)
 				;;
 		esac
 		[ "$REPLY" = "toggle_view_code" ] && toggle_view_code && continue
@@ -411,15 +389,12 @@ main() {
 }
 if ! command -v gum &> /dev/null; then
 	repo=charmbracelet/gum
-	command -v jq &> /dev/null || install_cmd_rootless jq
-	echo "Checking for the latest version of $repo..."
-	request=$(curl -s https://api.github.com/repos/$repo/releases/latest)
-	[ "$(echo -E "$request" | jq -er 'select(has("message")) | .message')" ] && return
-	latest_release=$(echo -E "$request" | jq -r ".tag_name")
-	echo "Downloading $repo..."
-	gum_latest_release=gum_${latest_release#v}_Linux_x86_64
-	download_url=$(echo -E "$request" | jq -r '.assets[].browser_download_url | select(endswith("Linux_x86_64.tar.gz"))')
-	wget -q --show-progress "$download_url"
+	echo "Downloading the latest version of $repo..."
+	download_url=$(curl -s https://api.github.com/repos/$repo/releases/latest | grep -Eo '"https://github.com/charmbracelet/gum/releases/download/[^"]*_Linux_x86_64\.tar\.gz"')
+	[ -z "$download_url" ] && { echo "Failed to download gum"; exit 1; }
+	url=$(echo "$download_url" | sed 's/^"//;s/"$//')
+	wget -q --show-progress "$url"
+	gum_latest_release=$(basename "$url" .tar.gz)
 	tar -xzf $gum_latest_release.tar.gz
 	mv $gum_latest_release/gum $HOME/.local/bin
 	rm -rf $gum_latest_release.tar.gz $gum_latest_release
